import React, { useState, useRef, useEffect } from "react";
import {
  Send,
  Download,
  Bot,
  User,
  Image as ImageIcon,
  X,
  FileText,
  BookOpen,
  Compass,
  ArrowUpRight,
  HelpCircle,
  Sparkles,
  Zap,
  AlertTriangle,
  RotateCcw,
} from "lucide-react";
import { ChatMessage, GeminiModelId } from "../types";
import { AVAILABLE_MODELS } from "../constants/models";
import ModelSelector from "./ModelSelector";
import ReactMarkdown from "react-markdown";
import { motion, AnimatePresence } from "motion/react";

interface ChatProps {
  messages: ChatMessage[];
  onSendMessage: (content: string, figureBase64?: string) => void;
  isLoading: boolean;
  selectedFigure: string | null;
  onClearFigure: () => void;
  onNavigateToPage: (pageNumber: number) => void;
  documentName?: string;
  quotedText?: string | null;
  onClearQuotedText?: () => void;
  selectedModel: GeminiModelId;
  onSelectModel: (model: GeminiModelId) => void;
  autoFallback: boolean;
  onToggleAutoFallback: (enabled: boolean) => void;
  onRetryWithModel?: (targetModel?: GeminiModelId) => void;
}

export default function Chat({
  messages,
  onSendMessage,
  isLoading,
  selectedFigure,
  onClearFigure,
  onNavigateToPage,
  documentName,
  quotedText,
  onClearQuotedText,
  selectedModel,
  onSelectModel,
  autoFallback,
  onToggleAutoFallback,
  onRetryWithModel,
}: ChatProps) {
  const [input, setInput] = useState("");
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // When quoted text is passed from PDF viewer selection, populate input
  useEffect(() => {
    if (quotedText) {
      setInput((prev) =>
        prev
          ? `${prev}\n\nRegarding this passage: "${quotedText}"`
          : `Explain this passage: "${quotedText}"`
      );
      if (onClearQuotedText) {
        onClearQuotedText();
      }
    }
  }, [quotedText, onClearQuotedText]);

  // Auto-scroll to bottom
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() && !selectedFigure) return;

    onSendMessage(input, selectedFigure || undefined);
    setInput("");
  };

  // Helper to extract cited page numbers from text
  const extractCitedPages = (content: string): number[] => {
    const regex = /\[(?:Page|p\.)\s*(\d+)/gi;
    const pages = new Set<number>();
    let match;
    while ((match = regex.exec(content)) !== null) {
      const pageNum = parseInt(match[1], 10);
      if (!isNaN(pageNum)) {
        pages.add(pageNum);
      }
    }
    return Array.from(pages).sort((a, b) => a - b);
  };

  // Pre-process markdown to convert [Page X] or [Page X: Topic] into active links [#page-X]
  const preprocessMarkdown = (content: string): string => {
    return content.replace(
      /\[(?:Page|p\.)\s*(\d+)(?::\s*([^\]]+))?\]/gi,
      (_match, p1, p2) => {
        const title = p2 ? `: ${p2.trim()}` : "";
        return `[Page ${p1}${title}](#page-${p1})`;
      }
    );
  };

  // Export structured Study Guide
  const handleExport = () => {
    if (messages.length === 0) return;

    const docTitle = documentName || "Document";
    const dateStr = new Date().toLocaleDateString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    let md = `# 📚 Study Guide: ${docTitle}\n`;
    md += `*Generated by Study Chat on ${dateStr}*\n\n`;
    md += `---\n\n`;
    md += `## 📑 Study Session Overview\n\n`;
    md += `This study guide contains questions, explanations, figure analyses, and page references generated during your interactive reading session.\n\n`;

    let questionCount = 1;
    messages.forEach((msg) => {
      if (msg.role === "user") {
        md += `\n### ❓ Question ${questionCount++}: ${msg.content || "Question about selected figure"}\n\n`;
        if (msg.figureBase64) {
          md += `> 🖼️ *Includes attached figure/diagram from the document*\n\n`;
        }
      } else {
        const citedPages = extractCitedPages(msg.content);
        md += `#### 💡 Key Explanation\n\n`;
        md += `${msg.content}\n\n`;
        if (citedPages.length > 0) {
          md += `**📍 Referenced Document Pages:** ${citedPages.map((p) => `Page ${p}`).join(", ")}\n\n`;
        }
        md += `---\n`;
      }
    });

    md += `\n\n## 📝 Quick Review Checklist\n\n`;
    md += `- [ ] Review all cited pages in the original document\n`;
    md += `- [ ] Test recall on key figures and formulas discussed\n`;
    md += `- [ ] Summarize main takeaways in your own words\n`;

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${docTitle.replace(/\.[^/.]+$/, "")}-study-guide.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="flex flex-col h-full bg-white">
      {/* Header */}
      <div className="p-4 border-b border-slate-100 shadow-2xs z-10 relative bg-white">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-slate-800 flex items-center gap-1.5">
              Study Chat
            </h2>
            <p className="text-xs text-slate-500">
              Click any <span className="font-medium text-blue-600">[Page X]</span> citation to jump directly to that section in the PDF
            </p>
          </div>
          <button
            onClick={handleExport}
            disabled={messages.length === 0}
            className="flex items-center px-3 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors disabled:opacity-40 cursor-pointer shadow-2xs"
            title="Export Study Guide as Markdown"
          >
            <Download className="w-3.5 h-3.5 mr-1.5" />
            Export Guide
          </button>
        </div>

        {/* Model Selection & Traffic Control Bar */}
        <div className="mt-3 pt-3 border-t border-slate-100 flex items-center justify-between gap-2 flex-wrap">
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold text-slate-600">Model:</span>
            <ModelSelector
              selectedModel={selectedModel}
              onSelectModel={onSelectModel}
              autoFallback={autoFallback}
              onToggleAutoFallback={onToggleAutoFallback}
              disabled={isLoading}
            />
          </div>

          {autoFallback ? (
            <div
              className="flex items-center gap-1 text-[11px] font-medium text-emerald-700 bg-emerald-50 px-2 py-1 rounded-md border border-emerald-200/70"
              title="If the selected model experiences a 503 high demand spike, queries will automatically route through Gemini 3.5 Flash Lite so you are never blocked."
            >
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
              Auto-bypass 503 active
            </div>
          ) : (
            <div
              className="flex items-center gap-1 text-[11px] font-medium text-slate-500 bg-slate-100 px-2 py-1 rounded-md"
              title="Manual mode: errors will be reported directly without automatic rerouting"
            >
              Manual model mode
            </div>
          )}
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {messages.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full text-slate-400 space-y-3 p-4">
            <Bot className="w-12 h-12 text-slate-300" />
            <p className="text-center max-w-sm text-sm text-slate-500">
              Upload a PDF to start studying. You can select figures or text to ask specific questions, and all AI answers will include clickable citations that navigate the document!
            </p>
          </div>
        ) : (
          messages.map((msg, idx) => {
            const citedPages = msg.role === "model" ? extractCitedPages(msg.content) : [];

            return (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
              >
                <div
                  className={`flex max-w-[90%] ${
                    msg.role === "user" ? "flex-row-reverse" : "flex-row"
                  }`}
                >
                  <div
                    className={`flex-shrink-0 h-8 w-8 rounded-full flex items-center justify-center mt-1 ${
                      msg.role === "user"
                        ? "ml-3 bg-blue-100 text-blue-600"
                        : "mr-3 bg-emerald-100 text-emerald-600"
                    }`}
                  >
                    {msg.role === "user" ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4 text-emerald-600" />}
                  </div>

                  <div
                    className={`flex flex-col ${
                      msg.role === "user" ? "items-end" : "items-start"
                    } w-full`}
                  >
                    {msg.figureBase64 && (
                      <div className="mb-2 p-1.5 bg-white rounded-lg shadow-sm border border-slate-200 inline-block">
                        <span className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider block mb-1">
                          Cropped Figure from Document
                        </span>
                        <img
                          src={msg.figureBase64}
                          alt="Selected figure"
                          className="max-w-full max-h-52 rounded object-contain border border-slate-100"
                        />
                      </div>
                    )}

                    <div
                      className={`px-4 py-3 rounded-2xl ${
                        msg.role === "user"
                          ? "bg-blue-600 text-white rounded-tr-xs"
                          : msg.isError
                          ? "bg-rose-50 text-rose-900 rounded-tl-xs border border-rose-200 shadow-2xs"
                          : "bg-slate-50 text-slate-800 rounded-tl-xs border border-slate-200/80 shadow-2xs"
                      }`}
                    >
                      {msg.role === "user" ? (
                        <p className="whitespace-pre-wrap text-sm leading-relaxed">{msg.content}</p>
                      ) : msg.isError ? (
                        <div className="space-y-2">
                          <div className="flex items-center gap-1.5 text-rose-700 font-semibold text-xs">
                            <AlertTriangle className="w-4 h-4 text-rose-600 shrink-0" />
                            <span>High Demand on Model</span>
                          </div>
                          <p className="text-xs text-rose-800 leading-relaxed">{msg.content}</p>
                          <div className="pt-2 flex flex-wrap items-center gap-2">
                            <button
                              type="button"
                              onClick={() => {
                                onSelectModel("gemini-3.5-flash-lite");
                                onRetryWithModel?.("gemini-3.5-flash-lite");
                              }}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-white hover:bg-rose-50 text-rose-800 border border-rose-300 shadow-2xs hover:scale-105 active:scale-95 transition-all cursor-pointer"
                            >
                              <Zap className="w-3.5 h-3.5 text-amber-500 fill-amber-500" />
                              Switch to Gemini 3.5 Flash Lite & Retry
                            </button>
                            <button
                              type="button"
                              onClick={() => onRetryWithModel?.()}
                              className="inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-medium bg-rose-100 hover:bg-rose-200 text-rose-700 transition-colors cursor-pointer"
                            >
                              <RotateCcw className="w-3 h-3" /> Retry Same
                            </button>
                          </div>
                        </div>
                      ) : (
                        <div className="markdown-body text-sm leading-relaxed">
                          <ReactMarkdown
                            components={{
                              a: ({ href, children, ...props }) => {
                                if (href?.startsWith("#page-")) {
                                  const pageNum = parseInt(href.replace("#page-", ""), 10);
                                  return (
                                    <button
                                      type="button"
                                      onClick={(e) => {
                                        e.preventDefault();
                                        e.stopPropagation();
                                        onNavigateToPage(pageNum);
                                      }}
                                      className="inline-flex items-center gap-1 px-2 py-0.5 mx-1 my-0.5 rounded-md text-xs font-semibold bg-blue-100 hover:bg-blue-200 text-blue-800 border border-blue-300 transition-all cursor-pointer shadow-2xs hover:scale-105 active:scale-95"
                                      title={`Click to jump to Page ${pageNum} in PDF`}
                                    >
                                      <FileText className="w-3 h-3 text-blue-600 shrink-0" />
                                      <span>{children}</span>
                                      <ArrowUpRight className="w-2.5 h-2.5 text-blue-500 opacity-70" />
                                    </button>
                                  );
                                }
                                return (
                                  <a
                                    href={href}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-blue-600 underline font-medium"
                                    {...props}
                                  >
                                    {children}
                                  </a>
                                );
                              },
                            }}
                          >
                            {preprocessMarkdown(msg.content)}
                          </ReactMarkdown>
                        </div>
                      )}

                      {/* Fallback Notice if auto-routed */}
                      {msg.fellBack && (
                        <div className="mt-2.5 pt-2 border-t border-slate-200/70 flex items-center gap-1.5 text-[11px] text-amber-700 bg-amber-50/70 -mx-1 px-2 py-1 rounded">
                          <Zap className="w-3 h-3 text-amber-600 shrink-0" />
                          <span>
                            Auto-routed to <strong>Gemini 3.5 Flash Lite</strong> (bypassed high demand on {msg.originalModel})
                          </span>
                        </div>
                      )}

                      {/* Interactive Bottom Citation Bar */}
                      {citedPages.length > 0 && !msg.isError && (
                        <div className="mt-3 pt-2.5 border-t border-slate-200/80 flex flex-wrap items-center gap-1.5 text-xs">
                          <span className="font-semibold text-slate-600 flex items-center gap-1">
                            <Compass className="w-3.5 h-3.5 text-blue-600" />
                            Jump to cited page:
                          </span>
                          {citedPages.map((page) => (
                            <button
                              key={page}
                              onClick={() => onNavigateToPage(page)}
                              className="px-2.5 py-1 rounded-md bg-white hover:bg-blue-50 text-blue-700 border border-blue-200 font-semibold hover:border-blue-400 transition-all flex items-center gap-1 cursor-pointer shadow-2xs hover:scale-105 active:scale-95"
                              title={`Jump PDF viewer to Page ${page}`}
                            >
                              <BookOpen className="w-3 h-3 text-blue-500" />
                              Page {page}
                            </button>
                          ))}
                        </div>
                      )}

                      {/* Model Attribution Footer */}
                      {msg.role === "model" && msg.modelUsed && !msg.isError && (
                        <div className="mt-2 flex items-center justify-end gap-1 text-[10px] text-slate-400">
                          <span>Answered by {msg.modelUsed}</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })
        )}

        {isLoading && (
          <div className="flex justify-start">
            <div className="flex max-w-[85%] flex-row">
              <div className="flex-shrink-0 h-8 w-8 rounded-full flex items-center justify-center mt-1 mr-3 bg-emerald-100 text-emerald-600">
                <Bot className="w-4 h-4 text-emerald-600" />
              </div>
              <div className="px-5 py-4 rounded-2xl bg-slate-50 text-slate-800 rounded-tl-xs border border-slate-200/80 flex space-x-1.5 items-center">
                <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                <div className="w-2 h-2 bg-slate-400 rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
                <span className="text-xs text-slate-500 ml-2 font-medium">Analyzing document and generating citations...</span>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-4 bg-white border-t border-slate-100">
        <form onSubmit={handleSubmit} className="relative">
          <AnimatePresence>
            {selectedFigure && (
              <motion.div
                initial={{ opacity: 0, y: 10, scale: 0.95 }}
                animate={{ opacity: 1, y: 0, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                className="absolute -top-26 left-0 p-2 bg-white rounded-xl shadow-lg border border-slate-200 flex items-start z-20 gap-2"
              >
                <img
                  src={selectedFigure}
                  alt="Selection"
                  className="h-20 object-contain rounded-md bg-slate-50 border border-slate-100"
                />
                <div className="flex flex-col justify-between h-full py-0.5">
                  <span className="text-xs font-semibold text-slate-700 flex items-center gap-1">
                    <Sparkles className="w-3 h-3 text-amber-500" /> Attached Figure
                  </span>
                  <span className="text-[10px] text-slate-400">
                    The AI will connect this figure to the document
                  </span>
                  <div className="flex gap-1 mt-1">
                    <button
                      type="button"
                      onClick={() => setInput("Explain this figure and how it relates to the rest of the paper.")}
                      className="text-[10px] text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded hover:bg-blue-100 font-medium"
                    >
                      "Explain this figure"
                    </button>
                  </div>
                </div>
                <button
                  type="button"
                  onClick={onClearFigure}
                  className="bg-slate-800 text-white rounded-full p-1 shadow-sm hover:bg-slate-700 cursor-pointer"
                  title="Remove figure"
                >
                  <X className="w-3 h-3" />
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          <div className="flex items-end bg-slate-50 rounded-xl border border-slate-200 focus-within:ring-2 focus-within:ring-blue-500/20 focus-within:border-blue-500 transition-all overflow-hidden p-1 shadow-2xs">
            <div className="flex-1 max-h-32 overflow-y-auto">
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleSubmit(e);
                  }
                }}
                placeholder={
                  selectedFigure
                    ? "Ask a question about the selected figure..."
                    : "Ask a question about the document (or select text in the PDF)..."
                }
                className="w-full bg-transparent border-0 focus:ring-0 resize-none p-3 text-sm text-slate-700 min-h-[52px]"
                rows={Math.min(4, input.split("\n").length || 1)}
              />
            </div>
            <button
              type="submit"
              disabled={isLoading || (!input.trim() && !selectedFigure)}
              className="p-3 m-1 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-40 disabled:hover:bg-blue-600 transition-colors shrink-0 cursor-pointer shadow-xs"
            >
              <Send className="w-4 h-4" />
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
